import {test} from "uvu"
import * as assert from "uvu/assert"
import "./gates.test.js"
import "./sr_latch.test.js"
import "./d_latch.test.js"
import "./d_flipflop.test.js"
import "./d_latch_display.test.js"
import "./and_edge_detector.test.js"
